Repository NationalBankBelgium/stark, pull requests merged in 2018-03, with the labels that each got.

#132 Add templates for PR and Issues #11
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: P1, must, type: admin

#145 feat(build): added .gitattributes. Closes #144.
  .gitattributes
Labels: PR action: review

#184 docs(commits): added rules for commit messages. closes #28
  CONTRIBUTING.md
Labels: PR action: review

#182 [#73] adapt package.json
  packages/stark-core/package.json
Labels: PR action: cleanup

#251 refactor(build): added missing rollup config
  package.json
  packages/rollup.config.js
  packages/stark-build/config/stylelint.config.js
  packages/stark-build/config/tslint.json
  packages/stark-build/tsconfig.json
  packages/stark-core/rollup.config.js
  packages/tsconfig.json
  starter/src/app/home/title/title.service.ts
Labels: PR action: review

#255 refactor(build): improved main build
  CONTRIBUTING.md
  build-functions.sh
  build.sh
  package.json
  packages/stark-build/config/webpack.common.js
  packages/stark-build/config/webpack.dev.js
  packages/stark-build/config/webpack.github-deploy.js
  packages/stark-build/config/webpack.prod.js
  packages/stark-build/config/webpack.test.js
Labels: PR action: review, comp: build-main

#267 feat(stark-testing): create separate stark-testing package and use it in all stark packages and starter
  build.sh
  package.json
  packages/stark-build/package.json
  packages/stark-core/karma.conf.typescript.js
  packages/stark-core/package.json
  packages/stark-core/tsconfig.json
  packages/stark-core/tsconfig.spec.json
  packages/stark-testing/helpers.js
  packages/stark-testing/karma.conf.typescript.js
  packages/stark-testing/package.json
  packages/stark-testing/rollup.config.js
  packages/tsconfig.json
  starter/karma.conf.typescript.js
  starter/package.json
  starter/tsconfig.json
  starter/tsconfig.spec.json
Labels: PR action: review

#284 docs(workflow): explained the proposed workflow with git flow
  CONTRIBUTING.md
Labels: comp: docs, type: doc
