Repository NationalBankBelgium/stark, pull requests merged in 2022-06, with the labels that each got.

#3392 fix(stark-ui): fix issue with table on action #3391
  packages/stark-ui/src/modules/table/components/table.component.html
  packages/stark-ui/src/modules/table/components/table.component.spec.ts
Labels: type: bug, comp: stark-ui, 10.x

#3390 fix(build-main): fix `npm run commit` script in order to fix the usage on Windows OS
  package.json
Labels: type: bug, comp: build-main, 10.x

#3389 fix(build-main): fix `npm run commit` script in order to fix the usage on Windows OS
  package.json
Labels: type: bug, comp: build-main, 12.x
