Repository NationalBankBelgium/stark, pull requests merged in 2022-09, with the labels that each got.

#3456 ci(build-main): disable failing MacOS runners
  .github/workflows/build.yml
Labels: type: bug, comp: ci & tooling

#3463 ci(build-main): disable failing MacOS runners
  .github/workflows/build.yml
Labels: comp: ci & tooling

#3453 fix(stark-ui): handles paste and drop event on the restrict-input directive
  packages/stark-ui/src/modules/restrict-input-directive/directives/restrict-input.directive.spec.ts
  packages/stark-ui/src/modules/restrict-input-directive/directives/restrict-input.directive.ts
Labels: type: bug, comp: stark-ui, 12.x
